### PR TITLE
The L pipe now accept multiple arguments.

### PR DESCRIPTION
**Pull request by loloof64**
I also updated the angular.ts comment with a more sophisticated example.

### CODE REVIEW

**Comment by rborn** [comment]
Do you mind updating the Readme example with the one you made in angular.ts and also clean the reflect-metadata from it ?

**Comment by rborn** [comment]
If it's too much hassle I can do it, just let me know :)

**Comment by loloof64** [comment]
No problem :smile: 
I update my PR with it :smile:

**Comment by jamlfy** [comment]
Yeah!

**Comment by rborn** [comment]
👍 🙇

**Comment by loloof64** [comment]
Thanks :smile:

**Pull request merged**
