### PR TITLE
Export NativeScript I18N as a NgModule to support Angular 2.0 stable

### PR DESCRIPTION
**Pull request by giordy**
Hello,

I've slightly modified your code to support Angular 2.0, which introduced NgModules.

### CODE REVIEW

**Comment by rborn** [comment]
Hi @giordy , I have a similar PR made by @andy-tai #13  - maybe you guys could decide what approach is better? :) sorry for the mess

**Comment by giordy** [comment]
Hi @rborn thanks for the feedback.

The reason why I decided to develop this pull request is that Angular 2 pushed NgModules as the preferred/encouraged way to publish APIs.

In @andy-tai approach only one module can "declare" (= add to the "declarations" section) the "L" pipe. If your app uses more than 1 module (very likely) and you put the "L" pipe in the declaration section of each model Angular will throw out an exception stating that only one module within the app can declare it. That's because the "declarations" section should be used for elements that belong to the module itself (but the "L" pipe comes from an external realm and don't live within the module where it is declared).

From my point of view wrapping the code in a module is the way to go, as "I18N" is a "cohesive block of functionality" (as stated https://angular.io/docs/ts/latest/guide/ngmodule.html) and simplifies importing the code where it is needed.

Cheers
Giordano

**Comment by rborn** [comment]
@giordy I pinged @andy-tai on his PR.
I don't know angular at all so I cannot judge :)

Thank you for helping :)

**Comment by andy-tai** [comment]
@rborn OK, this seems to be a more clean solution.

**Comment by rborn** [comment]
@andy-tai @giordy amazing, thanks so much :)

**Pull request merged**
